### ISSUE TITLE
Maptiles

### ISSUE THREAD

**Issue by Zaturrby** [HDAT/HDAT#1]
1. Natural Earth Map
 - Natural earth download
 - Geo-reference
 - Convert to tiles
 - Setup map-tiles server (?)
 - Load in Leaflet
2. Outline map
 - Natural Earth Outline
 - Illustrator Design

**Comment by evanzummeren** [comment]
Voor later
https://github.com/mapbox/tilemill#installation
https://github.com/mapbox/mbutil

**Comment by evanzummeren** [comment]
De tiles zijn nu seamless, maar nog niet bepaald perfect. Iets teveel wit denk ik. Wat meer zwart zou wrs al helpen. Ik ga er later nog een beetje mee experimenteren.
