### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by evanzummeren** [HDAT/HDAT#12]
7  Airhadji-Batavia 
  80  Amboina-Banda-Neira 
 134  Amboina-Batavia 
  39  Amboina-Makassar 
  61  Amboina-Ternate 
 671  Amsterdam-Batavia 
  39  Amsterdam-Colombo 
   4  Amsterdam-Hooghly 
 474  Amsterdam-Kaap de Goede Hoop 
   1  Arakan en Pegu-Colombo 
  40  Banda-Neira-Amboina 
 112  Banda-Neira-Batavia 
  17  Banda-Neira-Makassar 
  10  Banda-Neira-Ternate 
   1  Bandar Bushire-Basra 
  74  Bandjarmasin-Batavia 
   1  Bandjarmasin-Semarang 
   1  Bantaeng-Amboina 
 451  Bantam-Batavia 
   1  Bantam-Surat 
   3  Basra-Batavia 
   5  Basra-Gamron 
   3  Basra-Surat 
   2  Batavia-Airbangis 
  11  Batavia-Airhadji 
 123  Batavia-Amboina 
 362  Batavia-Amsterdam 
   3  Batavia-Ayutthaya 
 160  Batavia-Banda-Neira 
  91  Batavia-Bandjarmasin 
 516  Batavia-Bantam 
   4  Batavia-Baros 
   9  Batavia-Basra 
  17  Batavia-Bimlipatam 
 316  Batavia-Cheribon 
  10  Batavia-Cochin 
  58  Batavia-Colombo 
   1  Batavia-Danda Rajapur 
 138  Batavia-Delft 
 145  Batavia-Enkhuizen 
   1  Batavia-Galle 
  19  Batavia-Gamron 
  29  Batavia-Hooghly 
 151  Batavia-Hoorn 
   7  Batavia-Indramaju 
  19  Batavia-Jagannathpur 
  42  Batavia-Jambi 
  39  Batavia-Japara 
 218  Batavia-Kaap de Goede Hoop 
 118  Batavia-Kanton 
   1  Batavia-Kedah 
  15  Batavia-Kharg 
   2  Batavia-Lampong Toulang Bawang 
   6  Batavia-Ligor 
 157  Batavia-Makassar 
 176  Batavia-Malakka 
   1  Batavia-Masulipatnam 
   1  Batavia-Mauritius 
  22  Batavia-Mokka 
   1  Batavia-Muscat 
  75  Batavia-Nagapattinam 
  88  Batavia-Nagasaki 
 140  Batavia-Padang 
 158  Batavia-Palembang 
   1  Batavia-Palicol 
   2  Batavia-Pekalongan 
   4  Batavia-Pontianak 
   2  Batavia-Porto Novo 
  22  Batavia-Pulau Tjinkuk 
  18  Batavia-Pulicat 
   5  Batavia-Rembang 
 152  Batavia-Rotterdam 
  17  Batavia-Sadras 
 489  Batavia-Semarang 
  32  Batavia-Surabaja 
 124  Batavia-Surat 
  73  Batavia-Tegal 
 109  Batavia-Ternate 
 205  Batavia-Zeeland 
   7  Bima-Batavia 
  16  Bimlipatam-Batavia 
   1  Bimlipatam-Colombo 
   4  Cheribon-Amboina 
   3  Cheribon-Banda-Neira 
 547  Cheribon-Batavia 
   2  Cheribon-Makassar 
   1  Cheribon-Pamotangh 
   9  Cheribon-Semarang 
   9  Cochin-Batavia 
  47  Cochin-Colombo 
  31  Cochin-Galle 
   1  Cochin-Gamron 
   1  Cochin-Kanton 
   3  Cochin-Mokka 
   3  Cochin-Tuticorin 
   6  Colombo-Amsterdam 
  25  Colombo-Batavia 
  13  Colombo-Cochin 
   4  Colombo-Jaffna 
   2  Colombo-Kaap de Goede Hoop 
   2  Colombo-Kalpitiya 
   1  Colombo-Mokka 
  17  Colombo-Nagapattinam 
   2  Colombo-Rotterdam 
   6  Colombo-Surat 
   2  Colombo-Zeeland 
 129  Delft-Batavia 
  48  Delft-Kaap de Goede Hoop 
  85  Demak-Batavia 
   1  Demak-Malakka 
   7  Djoana-Amboina 
   6  Djoana-Banda-Neira 
   1  Djoana-Bandjarmasin 
  98  Djoana-Batavia 
   1  Djoana-Cheribon 
   3  Djoana-Makassar 
   1  Djoana-Malakka 
   4  Djoana-Ternate 
 112  Enkhuizen-Batavia 
  15  Enkhuizen-Kaap de Goede Hoop 
  70  Galle-Amsterdam 
  61  Galle-Batavia 
   4  Galle-Delft 
   4  Galle-Enkhuizen 
   1  Galle-Hooghly 
   4  Galle-Hoorn 
  31  Galle-Kaap de Goede Hoop 
   1  Galle-Malakka 
   7  Galle-Nagapattinam 
   4  Galle-Rotterdam 
   2  Galle-Surat 
  50  Galle-Zeeland 
   1  Gamron-Bandar Bushire 
   1  Gamron-Basra 
  13  Gamron-Batavia 
   6  Gamron-Cochin 
   7  Gamron-Colombo 
   2  Gamron-Galle 
   8  Gamron-Kharg 
   1  Gamron-Muscat 
   2  Gamron-Nagapattinam 
   9  Gamron-Surat 
   2  Gamron-Tuticorin 
   6  Gresik-Amboina 
  28  Gresik-Banda-Neira 
 110  Gresik-Batavia 
   2  Gresik-Makassar 
   1  Gresik-Pamanukan 
   1  Gresik-Ternate 
  21  Hooghly-Batavia 
   2  Hooghly-Galle 
 119  Hoorn-Batavia 
  59  Hoorn-Kaap de Goede Hoop 
   1  Indramaju-Amboina 
  15  Indramaju-Batavia 
   1  Jaffna-Colombo 
  51  Jaffna-Nagapattinam 
   2  Jagannathpur-Amsterdam 
   1  Jagannathpur-Balasore 
  19  Jagannathpur-Batavia 
   3  Jagannathpur-Zeeland 
  38  Jambi-Batavia 
   1  Jambi-Malakka 
   9  Jambi-Palembang 
   6  Japara-Amboina 
   5  Japara-Banda-Neira 
   1  Japara-Bandjarmasin 
 173  Japara-Batavia 
   1  Japara-Cheribon 
   5  Japara-Makassar 
   3  Japara-Malakka 
   1  Japara-Semarang 
  51  Kaap de Goede Hoop-Amsterdam 
 730  Kaap de Goede Hoop-Batavia 
   1  Kaap de Goede Hoop-Cochin 
  37  Kaap de Goede Hoop-Colombo 
  10  Kaap de Goede Hoop-Delft 
   9  Kaap de Goede Hoop-Enkhuizen 
   1  Kaap de Goede Hoop-Galle 
   1  Kaap de Goede Hoop-Hooghly 
   6  Kaap de Goede Hoop-Hoorn 
   4  Kaap de Goede Hoop-Kanton 
   4  Kaap de Goede Hoop-Nagapattinam 
   9  Kaap de Goede Hoop-Rotterdam 
  26  Kaap de Goede Hoop-Zeeland 
  16  Kanton-Amsterdam 
  63  Kanton-Batavia 
   3  Kanton-Colombo 
   3  Kanton-Delft 
   4  Kanton-Enkhuizen 
   2  Kanton-Hoorn 
   5  Kanton-Kaap de Goede Hoop 
   2  Kanton-Malakka 
   1  Kanton-Nagapattinam 
   3  Kanton-Rotterdam 
   3  Kanton-Surat 
  12  Kanton-Zeeland 
   1  Kayamkulam -Colombo 
   2  Kayamkulam -Galle 
   1  Kayamkulam -Tuticorin 
   1  Kedah-Batavia 
   1  Kedah-Malakka 
   1  Kelang-Banda-Neira 
  12  Kharg-Batavia 
   2  Kharg-Gamron 
   1  Ligor-Batavia 
  30  Makassar-Amboina 
  28  Makassar-Banda-Neira 
   1  Makassar-Bantam 
 172  Makassar-Batavia 
   2  Makassar-Ternate 
 111  Malakka-Batavia 
  10  Malakka-Colombo 
   2  Malakka-Hooghly 
   1  Malakka-Jagannathpur 
   4  Malakka-Kanton 
   5  Malakka-Nagapattinam 
   1  Malakka-Padang 
   3  Malakka-Palembang 
   6  Malakka-Surat 
  19  Masulipatnam-Batavia 
   7  Mokka-Batavia 
   2  Mokka-Cochin 
   3  Mokka-Colombo 
   7  Mokka-Galle 
   1  Muscat-Batavia 
   3  Nagapattinam-Amsterdam 
  92  Nagapattinam-Batavia 
   2  Nagapattinam-Cochin 
  34  Nagapattinam-Colombo 
   6  Nagapattinam-Galle 
  42  Nagapattinam-Jaffna 
   2  Nagapattinam-Malakka 
   1  Nagapattinam-Mannar 
   3  Nagapattinam-Mokka 
  21  Nagapattinam-Trincomale 
   3  Nagapattinam-Zeeland 
  84  Nagasaki-Batavia 
  25  Nagasaki-Malakka 
 147  Padang-Batavia 
 269  Palembang-Batavia 
   1  Palembang-Cheribon 
  10  Palembang-Jambi 
   2  Palembang-Malakka 
   2  Palembang-Semarang 
   1  Palicol-Amsterdam 
   5  Palicol-Batavia 
   1  Palicol-Zeeland 
   4  Pekalongan-Amboina 
   3  Pekalongan-Banda-Neira 
  95  Pekalongan-Batavia 
   1  Pekalongan-Malakka 
   1  Pekalongan-Pamanukan 
   1  Pekalongan-Semarang 
   9  Pontianak-Batavia 
   3  Porto Novo-Batavia 
  20  Pulau Tjinkuk-Batavia 
  26  Pulicat-Batavia 
   1  Pulicat-Malakka 
   1  Purakkad-Colombo 
   6  Purakkad-Galle 
   6  Quilon-Colombo 
   5  Quilon-Galle 
   7  Rembang-Amboina 
  17  Rembang-Banda-Neira 
   3  Rembang-Bandjarmasin 
 184  Rembang-Batavia 
   1  Rembang-Cheribon 
   6  Rembang-Makassar 
   1  Rembang-Malakka 
   2  Rembang-Semarang 
   4  Rembang-Ternate 
 120  Rotterdam-Batavia 
  73  Rotterdam-Kaap de Goede Hoop 
  17  Sadras-Batavia 
  26  Semarang-Amboina 
  34  Semarang-Banda-Neira 
   7  Semarang-Bandjarmasin 
 756  Semarang-Batavia 
   7  Semarang-Cheribon 
  22  Semarang-Makassar 
  14  Semarang-Malakka 
   1  Semarang-Palembang 
   6  Semarang-Ternate 
   1  Sumbawa-Batavia 
   4  Surabaja-Amboina 
  32  Surabaja-Banda-Neira 
 120  Surabaja-Batavia 
   1  Surabaja-Makassar 
   1  Surabaja-Pamanukan 
   6  Surakarta-Batavia 
   1  Surat-Basra 
 127  Surat-Batavia 
  16  Surat-Cochin 
  14  Surat-Colombo 
   7  Surat-Galle 
   1  Surat-Gamron 
   1  Surat-Kaap de Goede Hoop 
   3  Surat-Kanton 
   3  Surat-Malakka 
   3  Surat-Mokka 
   4  Surat-Tuticorin 
   7  Tegal-Amboina 
  11  Tegal-Banda-Neira 
 288  Tegal-Batavia 
   1  Tegal-Cheribon 
   1  Tegal-Makassar 
   2  Tegal-Malakka 
   1  Tegal-Pamanukan 
  25  Ternate-Amboina 
  12  Ternate-Banda-Neira 
 105  Ternate-Batavia 
   8  Trincomale-Nagapattinam 
  10  Tuticorin-Batavia 
   7  Tuticorin-Cochin 
   2  Tuticorin-Hooghly 
   5  Tuticorin-Nagapattinam 
   2  Tuticorin-Padang 
   1  Tuticorin-Surat 
 318  Zeeland-Batavia 
   9  Zeeland-Colombo 
   4  Zeeland-Galle 
 223  Zeeland-Kaap de Goede Hoop 

Totaal 323, zijn er vermoedelijk nog wat meer, maar dit geeft wel een redelijk idee. Bij het selecteren vielen er ineens een paar duizend reizen weg. Ga later nog even uitzoeken hoe en waarom

**Comment by Zaturrby** [comment]
Hoe heb je de lijst geconstrueerd?

**Comment by Zaturrby** [comment]
756 Semarang-Batavia
730 Kaap de Goede Hoop-Batavia
671 Amsterdam-Batavia
547 Cheribon-Batavia
516 Batavia-Bantam
489 Batavia-Semarang
474 Amsterdam-Kaap de Goede Hoop
451 Bantam-Batavia
362 Batavia-Amsterdam
318 Zeeland-Batavia
316 Batavia-Cheribon
288 Tegal-Batavia
269 Palembang-Batavia
223 Zeeland-Kaap de Goede Hoop
218 Batavia-Kaap de Goede Hoop
205 Batavia-Zeeland
184 Rembang-Batavia
176 Batavia-Malakka
173 Japara-Batavia
172 Makassar-Batavia
160 Batavia-Banda-Neira
158 Batavia-Palembang
157 Batavia-Makassar
152 Batavia-Rotterdam
151 Batavia-Hoorn
147 Padang-Batavia
145 Batavia-Enkhuizen
140 Batavia-Padang
138 Batavia-Delft
134 Amboina-Batavia
129 Delft-Batavia
127 Surat-Batavia
124 Batavia-Surat
123 Batavia-Amboina
120 Surabaja-Batavia
120 Rotterdam-Batavia
119 Hoorn-Batavia
118 Batavia-Kanton
112 Enkhuizen-Batavia
112 Banda-Neira-Batavia
111 Malakka-Batavia
110 Gresik-Batavia
109 Batavia-Ternate
105 Ternate-Batavia
98 Djoana-Batavia
95 Pekalongan-Batavia
92 Nagapattinam-Batavia
91 Batavia-Bandjarmasin
88 Batavia-Nagasaki
85 Demak-Batavia
84 Nagasaki-Batavia
80 Amboina-Banda-Neira
75 Batavia-Nagapattinam
74 Bandjarmasin-Batavia
73 Rotterdam-Kaap de Goede Hoop
73 Batavia-Tegal
70 Galle-Amsterdam
63 Kanton-Batavia
61 Galle-Batavia
61 Amboina-Ternate
59 Hoorn-Kaap de Goede Hoop
58 Batavia-Colombo
51 Kaap de Goede Hoop-Amsterdam
51 Jaffna-Nagapattinam
50 Galle-Zeeland
48 Delft-Kaap de Goede Hoop
47 Cochin-Colombo
42 Nagapattinam-Jaffna
42 Batavia-Jambi
40 Banda-Neira-Amboina
39 Batavia-Japara
39 Amsterdam-Colombo
39 Amboina-Makassar
38 Jambi-Batavia
37 Kaap de Goede Hoop-Colombo
34 Semarang-Banda-Neira
34 Nagapattinam-Colombo
32 Surabaja-Banda-Neira
32 Batavia-Surabaja
31 Galle-Kaap de Goede Hoop
31 Cochin-Galle
30 Makassar-Amboina
29 Batavia-Hooghly
28 Makassar-Banda-Neira
28 Gresik-Banda-Neira
26 Semarang-Amboina
26 Pulicat-Batavia
26 Kaap de Goede Hoop-Zeeland
25 Ternate-Amboina
25 Nagasaki-Malakka
25 Colombo-Batavia
22 Semarang-Makassar
22 Batavia-Pulau Tjinkuk
22 Batavia-Mokka
21 Nagapattinam-Trincomale
21 Hooghly-Batavia
20 Pulau Tjinkuk-Batavia
19 Masulipatnam-Batavia
19 Jagannathpur-Batavia
19 Batavia-Jagannathpur
19 Batavia-Gamron
18 Batavia-Pulicat
17 Sadras-Batavia
17 Rembang-Banda-Neira
17 Colombo-Nagapattinam
17 Batavia-Sadras
17 Batavia-Bimlipatam
17 Banda-Neira-Makassar
16 Surat-Cochin
16 Kanton-Amsterdam
16 Bimlipatam-Batavia
15 Indramaju-Batavia
15 Enkhuizen-Kaap de Goede Hoop
15 Batavia-Kharg
14 Surat-Colombo
14 Semarang-Malakka
13 Gamron-Batavia
13 Colombo-Cochin
12 Ternate-Banda-Neira
12 Kharg-Batavia
12 Kanton-Zeeland
11 Tegal-Banda-Neira
11 Batavia-Airhadji
10 Tuticorin-Batavia
10 Palembang-Jambi
10 Malakka-Colombo
10 Kaap de Goede Hoop-Delft
10 Batavia-Cochin
10 Banda-Neira-Ternate
9 Zeeland-Colombo
9 Pontianak-Batavia
9 Kaap de Goede Hoop-Rotterdam
9 Kaap de Goede Hoop-Enkhuizen
9 Jambi-Palembang
9 Gamron-Surat
9 Cochin-Batavia
9 Cheribon-Semarang
9 Batavia-Basra
8 Trincomale-Nagapattinam
8 Gamron-Kharg
7 Tuticorin-Cochin
7 Tegal-Amboina
7 Surat-Galle
7 Semarang-Cheribon
7 Semarang-Bandjarmasin
7 Rembang-Amboina
7 Mokka-Galle
7 Mokka-Batavia
7 Gamron-Colombo
7 Galle-Nagapattinam
7 Djoana-Amboina
7 Bima-Batavia
7 Batavia-Indramaju
7 Airhadji-Batavia
6 Surakarta-Batavia
6 Semarang-Ternate
6 Rembang-Makassar
6 Quilon-Colombo
6 Purakkad-Galle
6 Nagapattinam-Galle
6 Malakka-Surat
6 Kaap de Goede Hoop-Hoorn
6 Japara-Amboina
6 Gresik-Amboina
6 Gamron-Cochin
6 Djoana-Banda-Neira
6 Colombo-Surat
6 Colombo-Amsterdam
6 Batavia-Ligor
5 Tuticorin-Nagapattinam
5 Quilon-Galle
5 Palicol-Batavia
5 Malakka-Nagapattinam
5 Kanton-Kaap de Goede Hoop
5 Japara-Makassar
5 Japara-Banda-Neira
5 Batavia-Rembang
5 Basra-Gamron
4 Zeeland-Galle
4 Surat-Tuticorin
4 Surabaja-Amboina
4 Rembang-Ternate
4 Pekalongan-Amboina
4 Malakka-Kanton
4 Kanton-Enkhuizen
4 Kaap de Goede Hoop-Nagapattinam
4 Kaap de Goede Hoop-Kanton
4 Galle-Rotterdam
4 Galle-Hoorn
4 Galle-Enkhuizen
4 Galle-Delft
4 Djoana-Ternate
4 Colombo-Jaffna
4 Cheribon-Amboina
4 Batavia-Pontianak
4 Batavia-Baros
4 Amsterdam-Hooghly
3 Surat-Mokka
3 Surat-Malakka
3 Surat-Kanton
3 Rembang-Bandjarmasin
3 Porto Novo-Batavia
3 Pekalongan-Banda-Neira
3 Nagapattinam-Zeeland
3 Nagapattinam-Mokka
3 Nagapattinam-Amsterdam
3 Mokka-Colombo
3 Malakka-Palembang
3 Kanton-Surat
3 Kanton-Rotterdam
3 Kanton-Delft
3 Kanton-Colombo
3 Japara-Malakka
3 Jagannathpur-Zeeland
3 Djoana-Makassar
3 Cochin-Tuticorin
3 Cochin-Mokka
3 Cheribon-Banda-Neira
3 Batavia-Ayutthaya
3 Basra-Surat
3 Basra-Batavia
2 Tuticorin-Padang
2 Tuticorin-Hooghly
2 Tegal-Malakka
2 Rembang-Semarang
2 Palembang-Semarang
2 Palembang-Malakka
2 Nagapattinam-Malakka
2 Nagapattinam-Cochin
2 Mokka-Cochin
2 Malakka-Hooghly
2 Makassar-Ternate
2 Kharg-Gamron
2 Kayamkulam -Galle
2 Kanton-Malakka
2 Kanton-Hoorn
2 Jagannathpur-Amsterdam
2 Hooghly-Galle
2 Gresik-Makassar
2 Gamron-Tuticorin
2 Gamron-Nagapattinam
2 Gamron-Galle
2 Galle-Surat
2 Colombo-Zeeland
2 Colombo-Rotterdam
2 Colombo-Kalpitiya
2 Colombo-Kaap de Goede Hoop
2 Cheribon-Makassar
2 Batavia-Porto Novo
2 Batavia-Pekalongan
2 Batavia-Lampong Toulang Bawang
2 Batavia-Airbangis
1 Tuticorin-Surat
1 Tegal-Pamanukan
1 Tegal-Makassar
1 Tegal-Cheribon
1 Surat-Kaap de Goede Hoop
1 Surat-Gamron
1 Surat-Basra
1 Surabaja-Pamanukan
1 Surabaja-Makassar
1 Sumbawa-Batavia
1 Semarang-Palembang
1 Rembang-Malakka
1 Rembang-Cheribon
1 Purakkad-Colombo
1 Pulicat-Malakka
1 Pekalongan-Semarang
1 Pekalongan-Pamanukan
1 Pekalongan-Malakka
1 Palicol-Zeeland
1 Palicol-Amsterdam
1 Palembang-Cheribon
1 Nagapattinam-Mannar
1 Muscat-Batavia
1 Malakka-Padang
1 Malakka-Jagannathpur
1 Makassar-Bantam
1 Ligor-Batavia
1 Kelang-Banda-Neira
1 Kedah-Malakka
1 Kedah-Batavia
1 Kayamkulam -Tuticorin
1 Kayamkulam -Colombo
1 Kanton-Nagapattinam
1 Kaap de Goede Hoop-Hooghly
1 Kaap de Goede Hoop-Galle
1 Kaap de Goede Hoop-Cochin
1 Japara-Semarang
1 Japara-Cheribon
1 Japara-Bandjarmasin
1 Jambi-Malakka
1 Jagannathpur-Balasore
1 Jaffna-Colombo
1 Indramaju-Amboina
1 Gresik-Ternate
1 Gresik-Pamanukan
1 Gamron-Muscat
1 Gamron-Basra
1 Gamron-Bandar Bushire
1 Galle-Malakka
1 Galle-Hooghly
1 Djoana-Malakka
1 Djoana-Cheribon
1 Djoana-Bandjarmasin
1 Demak-Malakka
1 Colombo-Mokka
1 Cochin-Kanton
1 Cochin-Gamron
1 Cheribon-Pamotangh
1 Bimlipatam-Colombo
1 Batavia-Palicol
1 Batavia-Muscat
1 Batavia-Mauritius
1 Batavia-Masulipatnam
1 Batavia-Kedah
1 Batavia-Galle
1 Batavia-Danda Rajapur
1 Bantam-Surat
1 Bantaeng-Amboina
1 Bandjarmasin-Semarang
1 Bandar Bushire-Basra
1 Arakan en Pegu-Colombo

**Comment by Zaturrby** [comment]
Misschien interessant om dezelfde queries eens op regio's te draaien. Ik zit er even tussen te bladeren, en als ik alle interne java-reizen, en Nederland - Kaap - Java eruit haal daalt het aantal significant. van de 14264 reizen die jij eruit gehaald hebt, blijven er dan 6000 over. Gelukkig nog steeds een wel een interessant aantal.

**Comment by Zaturrby** [comment]
cat routes.txt | sort -gr | awk '{s+=$1} END {print s}' (is het commando dat ik er even overheen heb gegooid)

**Comment by evanzummeren** [comment]
Ja, het verschil zit hem inderdaad in regios en de places. Soms is er simpelweg geen place bekend. Ik heb ze in de sql zodanig aangepast dat ik de regio selecteer wanneer er geen place van bekend is. Daarnaast heb ik de das met de bgb gecombineerd, waardoor we nu op 583 routes zitten. Alle routes staan in een aparte tabel hdatRoutes, die via een id gekoppeld zijn met de andere voyages.

De gehele query is hier t ezien: https://github.com/HDAT/hdat-plan/blob/master/query.sql

Ik ben op een nieuw probleem gestuit, komt er kort gezegd op neer dat de voyages in de bgb dataset niet per se unieke voyages zijn. Een voyage kan bijvoorbeeld uit 5 verschillende das voyages bestaan. Waar DAS bijvoorbeeld Amsterdam naar Batavia als een reis ziet, ziet BGB dit als 3,4 of zelfs 5 reizen. Een entry is dan bijvoorbeeld de hele lading van Amsterdam naar Batavia. Een andere entry gaat over hetgeen dat in Kaap de Goede Hoop werd gedropt, entry nummer 3 gaat over hetgeen bij Kaap de Goede Hoop is meegenomen en bij Batavia werd gezet. Lastig om dit in een paar woorden goed uit te leggen, maar ik zal het nog wel laten zien.

**Comment by Zaturrby** [comment]
Ik dacht ik ga eerst even die query goed doorlezen, maarehmm, toch maar niet! Je hebt heel wat werk verzet! 

Voor zover ik het begrijp selecteer je een hoop velden, vult ze in via hun relationele keys, zet ze in een nieuwe tabel zet, renamed ze als nodig, en mikt je ze vervolgens bij elkaar in in een nieuwe tabel en verwijder je vervolgens alle tijdelijke tabellen. Tussendoor maak je nog even een routes tabel aan.

Jouw probleem is voor zover ik zie geen probleem, BGB maakt DAS accurater dan lijkt het me. Maar zoals met al deze data transformaties is controle het grootste probleem. Als DAS Amsterdam-Batavia is, dan zal BGB uiteindelijk ook Amsterdam -> Batavia zijn, er moet geen stuk Amsterdam-Kaap missen ofzo. Als dat klopt op het oog dan kunnen we denk ik wel aannemen dat het goed komt en manier toepassen die je al doet: de DAS nummers die genoemd worden niet overnemen. 

580 routes he... Ik zit serieus te denken het eerst maar eens zonder correcte geo-routes te visualiseren. Wie weet kunnen we het ook simpel algorimatisch oplossen. Kortste route op basis van de kustlijn, met een marge. Dan heb je gewoon een matrix met bereiken van geografische posities die 'verboden' zijn, aan de hand van de kustlijnen in geo-JSON. Is wiskundig en programmatisch misschien wat ingewikkelder, maar ik heb geen zin om 580 routes te tekenen. In eerste instantie hoeven we dan alleen aan de regio tabel een coördinaat toe te voegen, die we vervolgens uitbreiden met de verboden posities matrix. Gooi er vervolgens nog een mooie bezier-curve op het het ziet er ook nog vloeiend uit. Misschien zelfs ook makkelijker te verantwoorden, zeker omdat we het gewoonweg niet bekend is. 

Anyways, ik ga er nu niet verder naar kijken, dat komt vrijdag. Een dag in de week (anders kom ik helemaal in de penarie! Ik moet nog veel lezen en een paper eruit weten te persen.)

**Comment by evanzummeren** [comment]
Ja, die queries hebben best wel wat tijd in beslag genomen :p 

En je beschrijving klopt idd. Kort gezegd: Je maakt een tabel aan, selecteer wat je wilt hebben, als je iets uit een andere tabel wilt hebben maak je gebruik van 'relationele keys'. Bepaalde selects kan je nog uitbreiden met functies zoals concat, sum etc.

Wat betreft die routes, het lijkt mij idd teveel werk om dat allemaal zelf uit te zoeken. Maar ik zou het persoonlijk wel jammer vinden wanneer het geen 'realistische routes' worden. Ik heb nog een andere oplossing bedacht die ik je vrijdag wil voorleggen: crowdsourcing ;P (ook heel hip enzo!)

Hoe laat zullen we vrijdag afspreken? Ik ben rond 13:00 klaar met werkgroepen

**Comment by Zaturrby** [comment]
Rond die tijd is goed. Ik zal in het het atrium zijn. Of misschien het PCH; ook geen verkeerd idee.

**Comment by Zaturrby** [comment]
Ohja het zijn idd geen relationele key, maar foreign keys. 

Crowdsourcing is wel heel ambitieus, dan moet je ook weer een interface om routes te tekenen maken enzo. Maar ik denk dat het algoritmatische goed en redelijk oké te doen. Maar hoe precies is nu ook nog niet zo heel erg van belang. Eerst visualiseer je het gewoon hemelsbreed, wat ik sowieso al als tussenstap van plan was. Als dat werk gedaan is kijk je vervolgens verder.

**Comment by evanzummeren** [comment]
PCH kantine is alleen wel heel erg druk rond dat tijdstip. Misschien is bungehuis verstandiger.

Wat crowdsourcing betreft, is idd vrij ambitieus, maar crowd is misschien iets te breed genomen. Ik zat meer te denken aan seniorsourcing: een man of vrouw op leeftijd die het leuk vind om nog na zijn pensioen nog in het archief bezig te zijn. Daar zijn er echt plenty van. En wat interface betreft, dat hoeft niet zo heel fantastisch te zijn, die bestaat zelfs grotendeels al (http://dbsgeo.com/arc.js/, alleen dan zonder de bolling natuurlijk). Je hebt een dropdown met alle routes, klikt op een route, gaat tekenen en klaar is kees.

En om het in eerste principe hemelsbreed te doen is natuurlijk prima, maar in het huidige tempo zijn we daar volgende week al :)

**Comment by Zaturrby** [comment]
Bungehuis is ook goed, ben ik eigenlijk nog niet eens binnen geweest! Ik begin trouwens steeds meer te twijfelen aan de van te voren gedefinieerde routes. Maar goed, laten we volgende week maar eerst even afwachten :)
