### ISSUE TITLE
CartoDB-API + Cliwoc

### ISSUE THREAD

**Issue by Zaturrby** [HDAT/HDAT#15]
D'r is veel gebeurd zie ik. Ik snap 't alleen nog niet helemaal, of misschien beter; ik snap niet helemaal waarom. Mijn comments mogen wel een beetje veel zijn maar die van jouw zijn wat summier.

Voor zover ik het begrijp gebeurd er dit:
1. Je voegt een complexe SQL functie toe aan template_postgis voor web-mercator projecties. 
2. Vervolgens maak je een tabel.
3. Vervolgens zeg je importeer de CSV
4. Vervolgens voer je een transformatie uit die de coordinaten transformeren naar well known text formaat voor geografie (formaat: 4326)
5. Vervolgens voer je een transformatie uit met web-mercator (formaat: 3857).

De eerste drie snap ik, de laatste tast ik wat meer in het duister, waarom? Heeft torque dat formaat nodig? Jouw geuploade in CartoDB heeft de transformatie niet. 
Ohja, waarom gebruik je trouwens de template_postgis om de data in te laden en niet een schone db? (Ik vermoed een slim gesmokkel met de API) 

Daarnaast mis ik nog hoe de connectie met de SQL-API in zicht komt, daar had je het ook over op slack.  Kan ik wat testen verder of is het nog midden in het proces? Ik vermoed namelijk dat je naar een locale testversie van de cliwoc data in torque toewerkt. 

I like the script btw, dat was al een handleiding op zichzelf.

**Comment by evanzummeren** [comment]
Ik heb eigenlijk gewoon de stappen van ghibbelibibbeli gevolgd. Stap 4 is the_geom, die is in cartodb ook aanwezig, alleen ik denk dat CartoDB hem automatisch naar WKT omzet. Ik weet nog steeds niet hoe het precies in elkaar steekt, dat hele postgis is toch nog best wel complex, maar op Wikipedia las ik dat SRIDs codes (die de projectie weergeven) vrijwel altijd in WKT-formaat staan.

Stap 5 wordt binnen de cartodb.com tool normaliter ook automatisch gedaan. Het is een iets ander formaat dan WGS84/4326 maar volgens mij zijn de verschillen vrij minimaal. Ik geloof dat torque deze kolom gebruikt om de tiles te bepalen. Maar dit staat beter uitgelegd op cartodb.

En waarom zou ik een nieuwe database gebruiken? Alle postgis functies stonden er al op geïnstalleerd, ook de nieuwe sql api functies, ik had hem al in de sql-api staan, en het is toch best wel overzichtelijk zo :)
