### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by evanzummeren** [HDAT/HDAT#19]
Hij export nu valid json.

Ik kwam dit ook nog tegen, misschien wel boeiend voor ons?

http://oboejs.com/

**Comment by Zaturrby** [comment]
Top!

Oboe; misschien. Maar niet nu. Er moet nog zoveel clientside logica komen voordat de manier waarop wij data inladen uberhaubt in beeld komt. Tot die tijd kunnen we smokkelen. Hoe groot is de JSON trouwens?

**Comment by evanzummeren** [comment]
Ik heb nog even gekeken naar de error, maar ik kan hem eerlijk gezegd nog niet vinden. Enige wat ik weet is dat er iig iets mis is in het jaar 1742... Het helpt ook niet echt mee dat de json gigantisch groot is, en dat het allemaal niet op chronologische volgorde ligt. 

Denk jij dat het kriskras op volgorde liggen van de voyages veel impact op de performance heeft? Misschien nog wel eens best de moeite waard om te testen, en het zou het oplossen van dit probleem wrs ook een stuk makkelijk maken.

**Comment by Zaturrby** [comment]
Nee. Het niet chronologisch zijn heeft geen significante impact op performance, hij loopt iedere tick over de hele tracks array en die is gewoonweg te groot. Qua performance wil ik de halve code het liefst herschrijven. Goed. 

Hoe heb je precies de vorige opgelost ‘1’ error opgelost? Want er moet een goed algoritme te verzinnen zijn die ze allemaal afvangt. 

Wellicht is het ook de moeite waard om tests of checks te gaan schrijven. Checks in de code of het correcte data is die ingeladen wordt. Tests om te kijken of onze code doet wat wij ervan verwachten en die assumpties allemaal te automatiseren. De code wordt zo stilletjes aan zo complex dat dit echt waarde begint te krijgen. (Tests misschien niet voor Antwerpen, maar checks kunnen deze fouten nu ook al compenseren)

**Comment by evanzummeren** [comment]
Ik heb niet het idee dat het om precies hetzelfde gaat als de vorige keer. Toen was er sprake van een lege array. De json is nu enigszins gesorteerd, maar ik heb het nog steeds geen lege array gevonden.

Het probleem begint iig rond 15/16 juli 1742. In unix time stamp (+500 jaar) is dat ergens tussen de 8600342400 en de 8600428800. Ik heb zojuist nog even de reizen rond deze periode bekeken maar ik zie gewoon niets vreemds.

Ik heb het de vorige keer opgelost dmv ```WHERE "geometry" IS NOT NULL AND "time" IS NOT NULL```.

**Comment by evanzummeren** [comment]
Oke, de schuldige zit in een van deze 44 reizen.

https://gist.github.com/evanzummeren/cc4ff1453da92e8da62a

**Comment by evanzummeren** [comment]
Ok. Dit is iig een van de voyages waarbij het fout gaat.
```
[ 
  {
    "type": "Feature",
    "geometry": {
      "type": "MultiPoint",
      "coordinates": [
        [
          107.046197544793,
          -5.79635008281572
        ],
        [
          106.588662163044,
          -5.81478768363056
        ],
        [
          106.362712409853,
          -5.82389292777063
        ],
        [
          106.096362660175,
          -5.83462619684133
        ],
        [
          105.882408644413,
          -5.84324804094939
        ],
        [
          104.44931219835,
          -6.53499835898156
        ],
        [
          101.571264096452,
          -9.18950874422689
        ],
        [
          97.9946606300163,
          -11.4528281253308
        ],
        [
          91.8194312074982,
          -15.0434026990574
        ],
        [
          85.1831552443849,
          -17.6979130843027
        ],
        [
          74.5930559179851,
          -21.5679098038445
        ],
        [
          62.6058458625089,
          -25.6335020254571
        ],
        [
          50.0178781935298,
          -28.7211167367161
        ],
        [
          36.7875658603713,
          -31.6536783059658
        ],
        [
          36.340164155871,
          -31.7528470188121
        ],
        [
          28.6281129313688,
          -34.4632418332205
        ],
        [
          20.594726239179,
          -35.1617971977587
        ],
        [
          18.7225978622165,
          -34.7426639790358
        ],
        [
          18.2270983014336,
          -34.186031355559
        ],
        [
          18.3091729524126,
          -33.9150118060562
        ],
        [
          18.4249830635265,
          -33.9015193872029
        ],
        [
          14.5444648908899,
          -30.6482613643079
        ],
        [
          9.72012907515562,
          -26.5478140421487
        ],
        [
          2.70507808149652,
          -20.4900103327567
        ],
        [
          -2.42405288942735,
          -16.1228672498067
        ],
        [
          -10.6630469281444,
          -9.17925262064511
        ],
        [
          -19.1163500603541,
          -0.768811307133922
        ],
        [
          -20.919221122431,
          0.873150917348737
        ],
        [
          -29.0412423012133,
          8.27027001395567
        ],
        [
          -33.5131587187597,
          14.7471670617333
        ],
        [
          -35.222869042401,
          18.7999901408941
        ],
        [
          -36.7801817884476,
          25.8626653775515
        ],
        [
          -35.7133987452842,
          31.7061599934509
        ],
        [
          -30.8795380809502,
          39.6451213012783
        ],
        [
          -26.4424209851651,
          41.9643134865222
        ],
        [
          -18.5986492123651,
          45.1533902453596
        ],
        [
          -17.6596501474867,
          45.5679033460717
        ],
        [
          -11.0669998457492,
          48.47817239819
        ],
        [
          -7.28081935334226,
          49.3331163803464
        ],
        [
          -4.59240906784311,
          49.7593481485726
        ],
        [
          0.118960961209212,
          50.4196956830005
        ],
        [
          2.40957167611742,
          51.5459126178304
        ],
        [
          3.57396545619576,
          51.4600147160213
        ]
      ]
    },
    "properties": {
      "time": [
        8573126400,
        8573162914.15485,
        8573180945.90629,
        8573202201.37698,
        8573219275.2263,
        8573346061.05535,
        8573657334.93058,
        8573992049.02496,
        8574552306.2642,
        8575104783.73013,
        8575961643.6447,
        8576899779.52546,
        8577830559.4332,
        8578776631.66012,
        8578808177.88626,
        8579369626.03763,
        8579901626.43605,
        8580029216.38634,
        8580084451.95632,
        8580106773.95401,
        8580114560.48958,
        8580484296.92396,
        8580955878.00974,
        8581662261.91991,
        8582185183.59724,
        8583034044.0332,
        8583984418.17213,
        8584179269.9465,
        8585055268.20766,
        8585679246.12219,
        8586027812.77243,
        8586602621.86979,
        8587074912.63908,
        8587782784.82596,
        8588109911.06744,
        8588632351.05223,
        8588694849.64906,
        8589124131.53487,
        8589335348.94166,
        8589479518.54493,
        8589727919.50886,
        8589874709.49777,
        8589933326.73906
      ]
    }
  }]
```

**Comment by evanzummeren** [comment]
Ok, dit is dus echt vaag. Het probleem lijkt hem in de laatste timestamp te zitten:         ```8589933326.73906``` (GMT: Wed, 16 Mar 2242 12:35:26 GMT). Als ik er een paar tellen bij doe dan werkt hij nog steeds niet, maar zodra ik er 33 minuten bij doe dus ```8589935326.73906``` dan doet tie het gewoon!! Wat is dit?!?!

**Comment by evanzummeren** [comment]
Oke, dit is dus echt bizar. Ik heb de hele set uit de db gehaald, en handmatig die ene timestamp aangepast, en alles werkt gewoon weer. Dit is dus echt de enige timestamp die voor problemen zorgt.

**Comment by evanzummeren** [comment]
Haha... Ik zie zojuist dat al mijn berichten met oke beginnen.

**Comment by evanzummeren** [comment]
Maar goed, het zijn er dus wel 13 864 voyages. Als je dat in gedachten houdt dan vind ik het eigenlijk nog best soepel werken.

**Comment by Zaturrby** [comment]
Het is de enige timestamp met problemen; kun je de error eens pasten?

**Comment by evanzummeren** [comment]
Uncaught TypeError: Cannot read property '1' of undefinedL.Playback.TrackController.L.Class.extend.tock @ vendor.js:1971L.Playback.Clock.L.Class.extend.setCursor @ vendor.js:2097onSliderChange @ vendor.js:2298o.DomEvent.addListener.t.(anonymous function).s @ vendor.js:8

**Comment by Zaturrby** [comment]
Die 1 trekt mijn aandacht; eerder was het 0 toch?

**Comment by evanzummeren** [comment]
Ik heb geen idee. Ik ben nu de regio's aan het updaten, ben benieuwd of ik hetzelfde probleem vaker tegenkom nu we meer voyages hebben.

**Comment by evanzummeren** [comment]
Nope. Alleen weer een error op die éne timestamp. Anyhow. We hebben nu 3000 reizen erbij, en het mooie is dat het nu een stuk diverser oogt, dus daar ben ik best wel blij mee. Veel extra reizen naar het midden oosten, ceylon en de bengalen. Of het een place of een regio verbinding is staat ook in de json aangegeven. De verschillende reizen staan nu aangegeven als "placeplace", "regioplace", "placeregio" of "regioregio" verbinding.

**Comment by evanzummeren** [comment]
We zitten nu rond de 17812 voyages. Blijkbaar werkt dat ding wat ik gisteren geschreven had toch niet helemaal optimaal. Kaap de Goede Hoop komt zowel in places als in regios voor en daar gaat blijkbaar iets mis. Ik weet nog niet precies wat, maar ik heb het nu tijdelijk kunnen plossen.

**Comment by evanzummeren** [comment]
Heb nu vier jaar (1500 schepen), en de animatie werkt vrij soepel.
