### ISSUE TITLE
Topojson

### ISSUE THREAD

**Issue by evanzummeren** [HDAT/HDAT#22]
Ik heb eventjes naar topojson gekeken, maar ik denk dat het voor ons weinig zin heeft. Onze lijnen zijn vrij simpel, en wij hebben geen overlappende punten. Waar topojson bijvoorbeeld wel handig voor zou zijn is wanneer je een kaart met verschillende provinciën hebt waarbij de ene provincie de andere overlapt.

Mochten we nog wat winst willen maken dan kunnen we denk ik beter de punten wat afronden. Deze zijn nu heel erg specifiek, terwijl we maar een zoomlevel van max 7 hebben.

**Comment by evanzummeren** [comment]
Om dat laatste nog even kracht bij te zetten. Ik heb even een random coordinaat gepakt en hem hierin gegooid: http://www.liedman.net/gis-nerd-tools/ (eindelijk een fijne tool)

```
111.567275366434,-6.56125658798906
111.5672,-6.5612
111.567,-6.561
```
De laatste met drie cijfers achter de komma (of in dit geval punt) scheelt echt heel weinig met de eerste. In ons geval (zoom 7) is dat verschil helemaal verwaarloosbaar. Ik heb even snel wat zitten rekenen en ik denk dat het bij de grote reizen scheelt dit 0,5 tot 1 kb per reis. Best de moeite waard dus.

**Comment by evanzummeren** [comment]
Bij de Minard zal het waarschijnlijk helemaal een groot verschil zijn, omdat de properties daar niets voorstellen.

**Comment by Zaturrby** [comment]
Doe maar!

**Comment by evanzummeren** [comment]
Cool! Gooi het er nu op. Weet niet het exacte verschil voor de voyages.json, maar de minard.json ging van 30 mb naar 15 mb.

**Comment by evanzummeren** [comment]
Het formaat is trouwens denk ik niet echt het probleem. Alle voyages bij elkaar zijn nu 14,1 mb, maar de json gzip compressie is best wel indrukwekkend (2,3 mb, 84.7% kleiner).

**Comment by Zaturrby** [comment]
Gzip compressie, hoe zit dat in de uitvoering in elkaar? gulp gziped en de javascript unzipped?

**Comment by evanzummeren** [comment]
De compressie wordt door de server gedaan, bij apache moet je dat apart instellen in de htaccess, maar nginx doet dit standaard. Github pages draait op nginx, dus we gebruiken nu al standaard gzip compressie. Het unzippen wordt volgens mij door de browser afgehandeld.

**Comment by Zaturrby** [comment]
Hmm, dat zal vast een stukkie complexer zijn, ik zie nog niet helemaal hoe alles in elkaar grijpt. Maar goed, hoe browsers intern werken ga ik vandaag echt niet uitzoeken. Ik neem het vandaag maar gewoon even aan.

**Comment by evanzummeren** [comment]
All modern browsers support and automatically negotiate GZIP compression for all HTTP requests: our job is to ensure that the server is properly configured to serve the compressed resource when requested by the client.

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer#text-compression-with-gzip

**Comment by Zaturrby** [comment]
Nog steeds aannemen dus, wat er allemaal onder de html css en js laag gebeurt heb ik geen eens een basaal idee van. Maar sowieso hebben we geen controle over gh-pages. Dus geen verandering.

Daarnaast gingen we er altijd al vanuit dat de data het probleem niet was; het probleem lag hem er altijd in dat de tock trager was dan de tick. _ticks array knalde soms zelfs de browser eruit, door zijn volume. Die structuur moet anders.

**Comment by Zaturrby** [comment]
De rest is optimalisatie.
