### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by evanzummeren** [HDAT/HDAT#23]
Zullen we dit voor feedback gebruiken? Scheelt een hoop werk. Mocht je er geen tijd voor hebben dan kan ik het er eventueel inzetten.

http://formspree.io/

**Comment by Zaturrby** [comment]
Mail notificatie is leuk, maar ik heb liever data. Firebase callback is trouwens niet veel ingewikkelder hoor.

**Comment by evanzummeren** [comment]
Prima.
