### ISSUE TITLE
Data transformation - Torque

### ISSUE THREAD

**Issue by Zaturrby** [HDAT/HDAT#9]
1. Paths
 - Create data-model
 - Create table
 - Determine paths
2. Points
 - Create data-model
 - Generate paths with voyages -> Points

**Comment by evanzummeren** [comment]
http://blog.willj.net/2011/05/31/setting-up-postgresql-for-ruby-on-rails-development-on-os-x/

**Comment by Zaturrby** [comment]
mmm? Die snap ik niet. postgresql-ruby-rails is een stack waar we weinig vanaf weten.

**Comment by evanzummeren** [comment]
Hey, ja sorry! Was meer voor mij persoonlijk zodat ik het terug kan vinden, en het ging mij niet om het ruby gedeelte :p

Ik heb wat zitten goochelen met torque (zie ook de 'export' query), en ik kreeg er in eerste instantie niet zo heel erg veel uit. Een puntje dat maar niet bewoog. Vervolgens ben ik wat verder gaan proberen, en het werkt volgens mij als volgt: Je hebt een x coordinaat, een y coordinaat en daaraan vast zit een timestamp. Iedere rij in je db is dus als het ware een punt. (Dus reken uit 22 000 x 100 = 2 200 000 rijen hehe). In eerste instantie dacht ik dat je voor een voyage alle punten in dezelfde rij oid kon gooien.

Vervolgens heb ik cartodb gevraagd of dit klopte, en hoe we dit het beste konden aanpakken. De structuur klopt idd, en ik ben doorverwezen naar Postgis, dat is iets bovenop postgres (een extender schrijven ze zelf) waarmee je allerlei gis shit in je sql queries kan verwerken. Hoe handig! Volgens die luitjes van cartodb zijn met name de functies st_makeline en st_droppoints voor ons interessant. De eerste maakt een lijn tussen twee punten en de tweede kan die lijn evenredig in punten verdelen, waardoor je dus een vloeiende lijn krijgt. De timestamp is daardoor ook heel makkelijk omdat we gewoon een evenredig aantal telkens kunnen optellen.

Goed, dus vandaar dat postgresql. Ik ga kijken of ik de mysql dump makkelijk naar postgresql kan omzetten, wat syntax betreft zijn er maar kleine verschillen, en tis schijnbaar ook nog eens heel hip (google: mongodb vs postgresql)

**Comment by Zaturrby** [comment]
Dat tof! De coordinaten met timestamp had ik al in mijn hoofd. Maar dat de interpolatie logica niet in torque zelf zit is top, dat betekent dat het gemakkelijk manipuleren is! Ik heb even PostGIS bekeken, daar zit flink wat geografische logica in. Het zou me niet verbazen als er een functie voor voor de routes is zoals ik het voorstelde. Die 2.2 miljoen blijven daar wel steken, ook met de functies. Tenminste als je van te voren gedefinieerde routes gebruikt ;)

**Comment by Zaturrby** [comment]
Oke. Hoe komen we tot een correcte tabel?

1. Allereerst lijkt het me interessant om bgbPlace te transformeren naar geoBgbPlace. Een nieuwe tabel met de coordinaten erbij. Hopelijk kan een stuk automatisch, maar ik vermoed dat dit gewoon handwerk is. Gewoon een hoop queries schrijven die aan de id's de coordinaten toevoegt. Hierbij moet uitgekeken worden dat de coordinaten in een voor postgis te gebruiken formaat staan.
2. Vervolgens moeten we die coordinaten samen met de reizen transformeren met correcte linestrings (laten we even 100 per reis aannemen). bgbVoyage -> geoBgbVoyage
3. Als derde stap moeten de linestrings in geoBgbVoyage uitgelezen worden naar een correct formaat voor cartoDB en daar worden geïmporteerd.

Laten we nog geen concatenatie van DAS erbij doen. De foreign keys daarin zijn gewoon zwakker, vooral voor de reizen die geen bgb equivalent hebben.

**Comment by evanzummeren** [comment]
Wel een beetje een overkill aan notificiaties, rj. haha. Ik heb de nieuwe gulp nog niet geprobeerd, maar ik zal hem een dezer dagen even proberen. Ik wil deze week toch al een beetje voor de tentamenweek voorbereiden, dus ik ga proberen niet al te veel te doen.

Hoe dan ook. Ik ben gisteren in de trein en zojuist nog even bezig geweest met cliwoc. Ik heb de DAS reizen kunnen exporteren, en deze draaiend gekregen in torque. Daarnaast kwam ik nog een hele interessante tabel tegen in cliwoc. 1500 plaatsnamen met de coordinaten :) Maw de oplossing voor punt 1. Ik kan een query schrijven die deze coordinaten samenvoegt met de bgbPlaces tabel en deze exporteren naar een csv bestand. Ik denk dat het niet verstandig is om die cliwoc ook in de gulp te zetten want het dump bestand is gigantisch (>800 mb). Ik heb er meer dan twee uur over gedaan om hem te importeren.

Ik moet er nu vandoor, maar op de rest zal ik later reageren

**Comment by Zaturrby** [comment]
:D Ik vind het wel prettig om al mijn handelingen uit te loggen. Ik ga ook niet meer teveel doen na wat ik net allemaal heb gedaan. 

Hoe heb je ze trouwens draaiend in torque gekregen? Ik dacht dat je eerder ook al zoiets zei, maar voor zover ik zie lijkt cartoDB wel een belangrijke spil te zijn. Waar kan ik het bekijken?

**Comment by Zaturrby** [comment]
Over samenvoeging trouwens; er zijn 150 plaatsen. Dat is een getal dat net op het randje zit. Handmatig ben je denk ik sneller af. Zeker omdat je dan op het oog goed inschatten wat de historische locatie is, je geen problemen met regexp hebt (tenzij cliwoc netjes de foreign keys van bgb hanteert), en je de notatie perfect kan afstemmen op wat postgis nodig heeft. Daarbij voel ik niet zoveel voor de handmatige import van een csv zoals je weet, zeker omdat het in de build niet eens gemakkelijk kán. Als je het wil; maak er dan een postgresql-dump van :)

**Comment by Zaturrby** [comment]
Kun je misschien een dump maken van die specifieke tabel? Dan kun je de transformatie binnen postgis draaien.

**Comment by evanzummeren** [comment]
Zal ik asap doen. Ik heb hdat geupdatet met daarin torque. Hij speelt nu de helft van de schepen af (probleempjes met cartodb, kan blijkbaar niet alle 8000 rijen importeren, heb ze al een berichtje gestuurd).

Anyhows, het meest interessante zit tussen 1750 en 1760.

**Comment by evanzummeren** [comment]
Ah ja, het database connectie dingetje werkt nog niet helemaal bij mij. Misschien is het slechts een kwestie van een user aanmaken, want hij zeurt nu om rj korteshciel.

**Comment by evanzummeren** [comment]
Maar goed, dat is voor nu niet zo belangrijk

**Comment by Zaturrby** [comment]
Ah, ik zie hem, ik heb hem niet is postgresadmin geupdated.

**Comment by evanzummeren** [comment]
Wat heb je niet?

Verstuurd vanaf mijn iPhone

**Comment by Zaturrby** [comment]
Oeps, dat was geen goede zin. Express-admin had de foute user staan, maar dat is nu weg.

**Comment by Zaturrby** [comment]
Even wat cleanup gedaan -> heb nu nog een apart vendor map gemaakt in client en die in gulp op ignore gezet. Dan is de JShint weer wat zinvoller. Ze worden nu in de vendor concat meegenomen. 

Ohja Erik, je kan heel makkelijk op de issue committen door #issuenumber te doen. In dit geval #9.

**Comment by Zaturrby** [comment]
Het geeft al wel een mooie indruk. Hoeveel punten per reis zijn er gebruikt?

**Comment by evanzummeren** [comment]
Ow wacht, dat had nummer 3 moeten zijn (mijn maxbounds). Ehm, ik heb geen idee eerlijk gezegd. Ik zal de csv zo even in de hdat-plan map zetten, maar het zijn er wel redelijk wat. Het geeft idd best een mooie indruk, ik vind het vooral cool dat je ook kan zien hoe ze tegen java aanvaarden wanneer ze naar batavia gingen. Misschien een idee om de hele cliwoc dataset erin te gooien, hoewel ik natuurlijk snel tegen het 50mb limiet aanloop.

Nog even snel over jouw idee om cartodb als server/api/wat dan ook te gebruiken. Ik denk dat we nog wel even goed moeten uitzoeken of er echt geen alternatieven bestaan. Het probleem is dat je namelijk al snel tegen limieten (zaken als fair use policy) aanloopt en zelfs limieten aan rijen. Ik las ergens wel dat je hier een soort van vrijstelling voor kan krijgen, maar goed, het is wel irritant.

**Comment by evanzummeren** [comment]
https://github.com/HDAT/hdat-plan/blob/master/data/cliwoc2.csv

De eerste heeft er 219 ... Ik denk dat we tegen die tijd ook goed moeten kijken hoeveel punten een reis nodig heeft. Wat ik wil zeggen is dat niet iedere reis er natuurlijk 100 of 200 nodig heeft. Reizen binnen Azie (10000 ofzo?) hoeven er misschien maar 20 of 30 te hebben.

**Comment by evanzummeren** [comment]
Ok, de hele set staat er nu op. Hoewel hij eigenlijk iets te groot was voor mijn gratis account, dus volgens mij heeft tie er nog wat uitgehaald.

Wat heel irritant is, is dat cartodb er best veel zooi bijgooit. Het oorspronkelijk csv bestand was 15mb, vervolgens is de sql db rond de 36 mb (er komt een cartodb id bij, een created_at en een updated_at timestamp die je niet kan verwijderen). Vervolgens moet je de x en y combineren in een nieuwe kolom, waarna ik dus aan mijn 50mb limiet kwam.

**Comment by Zaturrby** [comment]
Een boel, en waarschijnlijk teveel, punten in ieder geval. We hebben nog veel vraagstukken om op te lossen. Maar laten we eerst gewoon met de huidige stack alles werkende gaan krijgen. Want zodra we in alternatieven gaan duiken is het hek van de dam. 

Allereerst moet je serverside bouwen. Queries kunnen alleen daar worden gedraaid omdat je de wachtwoorden anders niet kan verstoppen en de databases zelf daar moeten draaien. Dat is veel werk. Deployment wordt veel ingewikkelder en je moet server/client logica bouwen. Dan als kersje op de taart moet je Torque openbreken, want die is helemaal gebouwd op CartoDB en hun SQL-api. Nou vind ik dat helemaal niet zo erg, want ik ben nog steeds niet zo weg van Torque. Ik zou er alleen niet aan beginnen. Ik denk dat we onze visualisatie efficienter, betekenisvoller en stijlvoller kunnen doen met custom code. Het gebrek aan interpolatie in torque maakt het dodelijk inefficient. Daarbij zijn 9 schepen die op dezelfde tijd vertrekken waarschijnlijk ononderscheidbaar.  

Ik vermoed dat het veel werk is en ook nog niet eens zo heelveel goedkoper zal zijn ook. Desalniettemin wel heel leerzaam! Maar ik denk dat het voor nu verstandig is om voor de eerste versie gewoon lekker met static/torque/CartoDB door te gaan. De logica die we moeten hebben om het daar werkende te krijgen is in grote lijnen ook het begin van de logica die we nodig hebben als we het met een eigen oplossing willen doen en dan zien we tenminste al wat en hebben we iets wat we kunnen presenteren. 

Wat we misschien wel kunnen doen is die kerel van de vliegtuig simulator een benaderen en vragen hoe hij het heeft gedaan. Dat komt namelijk veel dichter in de buurt van wat wij nodig hebben (zeker voor hemelsbreed). Jan Hein kende hem ofzo en had iets aangeboden.

**Comment by Zaturrby** [comment]
Ik vind de cliwoc data trouwens wel heel interessant, net zoals jij zegt hoe dat werkelijk ging. Niet zozeer vanuit technisch opzicht maar vanuit narratief perspectief. Waar wij de routes generaliseren zouden we als onderdeel van het verhaal een enkele route hieruit kunnen uitvergroten.

**Comment by evanzummeren** [comment]
Oke, ik ben vandaag bezig geweest met het transformeren van de cliwoc data naar het juiste formaat voor de sql api en torque. Was nog best een gepiel, maar volgens mij moet het zo werken. Check:

https://github.com/HDAT/hdat-plan/tree/master/cliwoc

Heb zelfs nog een uiterst professioneel bashscriptje bijgeschreven ;P

**Comment by evanzummeren** [comment]
Oh ja, de lat en long wordt omgezet naar iets dat Well-Known text heet. Ziet er niet zo heel toegankelijk uit (vb: 0101000020E61000004F401361C3234EC052499D8026222E40), maar goed, daar hebben we niet zo heel veel last van

**Comment by evanzummeren** [comment]
Dit heeft mij een aanzienlijk deel van mijn weekend gekost, maar vrijwel de gehele data transformatie staat nu netjes gedocumenteerd in een shell bestand. Ik heb geen idee of je dit ook in de gulp kan zetten, hoewel het misschien verstandiger is om dit apart te houden.

Gewoon het shell bestand uitvoeren en de rest wijst zich vanzelf :p

Ik ben ook nog bezig geweest met de coordinaten. In eerste instantie wilde ik gebruik maken van de cliwoc coordinaten, maar bij nader inzien zijn die toch niet zo volledig als ik dacht. Ik heb wel iets anders gevonden dat voor ons vrijwel perfect is, namelijk Atlas of Mutual Heritage. Daar staan letterlijk alle locaties in die we nodig hebben. Ik heb ze net een mailtje gestuurd, hopelijk doen ze niet moeiljk.

Tot slot, no offence maar dat express-admin is echt waardeloos. Zelfs PhpMyAdmin is daarmee in vergelijking nog een technisch en visueel hoogstandje.

**Comment by evanzummeren** [comment]
Best een productief dagje. Ik heb het stap per x km ding nog werkend gekregen, en ik denk dat ik ook een oplossing voor de departure en arrival heb gevonden. Dat laatste was eigenlijk verbazingwekkend simpel, dermate simpel dat ik me haast begin af te vragen of het wel klopt. Kan je er dus eventjes goed naar kijken? :) Het idee is dat we of arrival hebben of een departure (bij bgb is dat altijd het geval, bij das niet). Var $3 = dep, var $4 = arrival

```
      	CASE WHEN $3 IS NOT NULL THEN $3 + interval '1h' * increment
			 WHEN $4 IS NOT NULL THEN $4 - interval '1h' * increment
		END
```

**Comment by evanzummeren** [comment]
Hoeveel tabs hou jij trouwens aan? 2 toch? Misschien wel handig om dat een beetje af te stemmen

**Comment by evanzummeren** [comment]
Regio en place merge is zojuist ook gelukt. Weer met een CASE-expressie :). Ik kon bgbRegio en bgbPlace makkelijk mergen omdat ze dezelfde structuur hebben (id, naam). Daarnaast is de id altijd vele malen hoger (boven de 3000), het blijft daardoor makkelijk te zien wanneer iets een regio is of een place.

Vervolgens heb ik in torqueTable.sql bij de INSERT INTO 'voyagePoints' SELECT het volgende geplaatst:

```sql
	CASE WHEN "voyDeparturePlaceId" IS NOT NULL THEN "voyDeparturePlaceId"
			 WHEN "voyDeparturePlaceId" IS NULL THEN "voyDepartureRegioId"
	END,
	CASE WHEN "voyArrivalPlaceId" IS NOT NULL THEN "voyArrivalPlaceId"
			 WHEN "voyArrivalPlaceId" IS NULL THEN "voyArrivalRegioId"
	END,
```
Dus wanneer Place niet leeg is vul dan place in. Wanneer Place wél leeg is maak dan gebruik van de regio.

**Comment by evanzummeren** [comment]
Het resultaat is overigens in voyagePoints te zien

```csv
349,99703,861,3082,"0101000020E61000006669A7E672BB18C0D6E253008CB55A40","0101000020E610000019E76F4221221D40289B728577275440","0102000020E61000000200000019E76F4221221D40289B7285772754406669A7E672BB18C0D6E253008CB55A40","1787-05-01 00:00:00",NULL
```
861 is de oude place code (Batavia, in dit geval de departure place). De arrival was voorheen onbekend, maar is nu 3082 (de regio Ceylon).

**Comment by evanzummeren** [comment]
Ok, een heel vreemd probleem. Voor windshaft hebben we een kolom genaamd the_geom_webmercator nodig. Ze hebben een speciale pgplsqlfunctie gemaakt waarmee je die kan maken (cartodb_TransformToWebmercator). Wanneer ik deze draai dan geeft hij voor heel veel punten een null aan.

Bv voor dit punt
```
SELECT CDB_TransformToWebmercator('0101000020E610000098135C58E15113C00F515432021D5A40');
```

Wanneer ik dit punt omzet naar leesbare coordinaten met behulp van ``` SELECT ST_asText('0101000020E610000098135C58E15113C00F515432021D5A40'); ``` krijg ik een punt in Indonesie te zien.
http://www.darrinward.com/lat-long/?id=516546

Met het punt zelf lijkt dus niets mis te zijn. Ik snap het niet.

**Comment by Zaturrby** [comment]
Ik zie een verschil van 100000 punten in de huidige setup. 1/3 van je shit gaat mis. Ik zal eens even kijken naar een manier om het te console.loggen.

**Comment by Zaturrby** [comment]
Ik zie iets bijzonders in geometry type
